apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-oauth-config-onha
  namespace: ds2
data:
  SC_AUTH_HOST: "https://onhalogin.security365.com"
  SC_AUTH_PORT: "9000"
  SC_AUTH_INNER_URL: "http://0.0.0.0:8080"
  SC_AUTH_LOG_PATH: "/usr/local/tomcat/logs/SCCloudOAuthService"
  ELASTIC_HOST: "onha-cloud-oauth-elasticsearch.ds2.svc.cluster.local"
  ELASTIC_PORT: "9200"
  ELASTIC_ISHTTPS: "0"
  ELASTIC_CLUSTERNAME: "onha-cloud-oauth-elasticsearch"
 # ELASTIC_USERNAME: "elastic01"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-oauth-service-onha
  namespace: ds2
  labels:
    app: cloud-oauth-service-onha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-oauth-service-onha
  template:
    metadata:
      labels:
        app: cloud-oauth-service-onha
    spec:
      containers:
      - name: cloud-oauth-service-onha
        image: onha.security365.com/security365/cloud-oauth-service:20220120.1
        imagePullPolicy: Always
        resources:
          requests:
            memory: 2Gi
          limits:
            memory: 2Gi
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: cloud-oauth-config-onha
      imagePullSecrets:
      - name : test123-secret
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-oauth-service-onha
  namespace: ds2
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: cloud-oauth-service-onha
